/* eslint-disable react/require-default-props */
import React from 'react';
import Head from 'next/head';

interface SeoProps {
  title: string;
  description?: string;
  icon?: string;
}

const Seo: React.FC<SeoProps> = ({
  title,
  description = 'Generated by create next app',
  icon = '/favicon.ico',
}) => (
  <Head>
    <title>{title}</title>
    <meta name="description" content={description} />
    <link rel="icon" href={icon} />
  </Head>
);

export default Seo;
